### PR TITLE
Make transitionTo work with url as an argument

### PR DESCRIPTION
**Pull request by SergeAstapov**
@villander this recreates #32 since as you mentioned https://github.com/ember-engines/ember-engines/issues/587#issuecomment-483531420 does not happen.

### CODE REVIEW

**Comment by villander** [comment]
@SergeAstapov are you sure that it will work? Because we have a native error here from ember core codebase - https://github.com/emberjs/ember.js/blob/cf7c1bdebcd6af2e9d269ef3fd7946a29455c5df/packages/%40ember/-internals/routing/lib/utils.ts#L214

**Comment by SergeAstapov** [comment]
@villander it worked for me and I believe it's not an issue here because we do
```js
    if (resemblesURL(routeName)) {
      return get(this, 'externalRouter').transitionTo(routeName);
    }
```
so `transitionTo` is called on the `externalRouter` where we should have `owner.routable = false` because owner for the externalRouter is the host app, according to https://github.com/villander/ember-engines-router-service/blob/7eadf23d6b7e47ad6c108cc27dfceed03d7ec0c9/addon/services/engine-router-service.js#L52

Anyways, let me double check to make sure it works as intended.

**Comment by villander** [comment]
That makes sense @SergeAstapov

Thank you so much for push it forward ; )

**Comment by SergeAstapov** [comment]
@villander do you think you could release a patch version?

**Comment by villander** [comment]
@SergeAstapov sorry for delay, it's released now 🚀 

https://github.com/villander/ember-engines-router-service/releases/tag/v0.3.0

**Pull request merged**
