### PR TITLE
Run `npx ember-cli-update --to=3.28.5` to sync addon blueprint

### PR DESCRIPTION
**Pull request by SergeAstapov**
We can't land #50 due to `ember-engines` issues with Ember v4, more details see [#795](https://github.com/ember-engines/ember-engines/issues/795)

So instead of going all the way to 4.1, decided to upgrade addon blueprint to 3.28 and disable release/beta/canary tests due to above mentioned issue.

I'll rebase #50 and keep it open/WIP until https://github.com/ember-engines/ember-engines/issues/795 is fixed.

### CODE REVIEW

**Comment by SergeAstapov** [comment]
@villander the only failure before and after the PR is in 3.12 scenario

```
EEXIST: file already exists, symlink '/home/runner/work/ember-engines-router-service/ember-engines-router-service/tests/dummy/lib/ember-blog/addon/components/hello-name.js' -> '/tmp/broccoli-1695YTjFqLjnsl3F/out-082-template_compiler/ember-blog/components/hello-name.js'
[44](https://github.com/villander/ember-engines-router-service/runs/5046982678?check_suite_focus=true#step:5:44)
```

@villander I wonder if you up to converting this repo to monorepo so that test app, test engines will be just normal packages whiting monorepo instead of `link:./tests/dummy/lib/*`?
This will also prepare for v2 addon migration which should be relatively easy lift as this addon is small and only has a few js files.

**Comment by villander** [comment]
> the only failure before and after the PR is in 3.12 scenario

@SergeAstapov why it's failing? Is not possible to solve this issue?

> I wonder if you up to converting this repo to monorepo so that test app

Sure, that's my plan. I really want to turn this addon to V2 format 😄

**Comment by SergeAstapov** [comment]
> why it's failing? Is not possible to solve this issue?

TBH I'm not sure what's happening here. I feel it would take quite some time to find root case hence I disabled that test scenario for the time being to have green CI

**Review by villander — APPROVED** [review]
thank you!

**Pull request merged**
